# Generated by Django 5.2.15 on 2026-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
